FROM ubuntu:20.04

RUN apt update && \
    apt install --no-install-recommends -y vim \
                                           git \
                                           python \
                                           wget \
# [WARNING] will only work with open Github repositories
RUN git clone https://github.com/stelviopas/TMPipeline.git
RUN cd Mpipeline/anvil
RUN apt install -y fort77 csh

RUN wget http://www.bioinf.manchester.ac.uk/naccess/download/naccess.tar.gz.nc.gz
RUN unzip naccess.tar.gz.nc.gz
# [TODO] put the activation key here after the -k argument
RUN mcrypt -d -k "" < naccess.tar.gz.nc > naccess.tar.gz
